### PR TITLE
Update to Django 1.8

### PR DESCRIPTION
**Pull request by jwhitlock**
Update to Django 1.8 and switch from jingo to the new Jinja2 template backend.  Includes:

* Change bad uses of Django library as detected by the updated ``./manage.py check``
* Switch from jingo context variables to Jinja2 backend versions
* Switch template names and paths to Jinja2 backend preferences

### CODE REVIEW

**Comment by groovecoder** [comment]
Need rebase now. :cry:

**Comment by jwhitlock** [comment]
Rebased

**Comment by jwhitlock** [comment]
Rebased again, and:
* Update to Django 1.8.5 (just released)
* Change setting connection's debug cursor to 1.8 code
* Add some ``# pragma: no cover`` to lines copied from DRF code

**Comment by jwhitlock** [comment]
Rebased on master

**Comment by jezdez** [comment]
This looks good in general, but I think we should normalize the project to use django-jinja to make sure we use the same technique as kuma and other Mozilla projects. That can happen later though. r+

**Comment by jwhitlock** [comment]
Rebased on current master before merging.

Until the project supports localization, I don't see the need for Babel or django-jinja.  Converting to django-jinja would be a great first commit for @jezdez or @robhudson.

**Comment by jezdez** [comment]
@jwhitlock Good idea!

**Pull request merged**
